#!/usr/bin/env bash
# ================================
# PROD BUILD - Alça Finanças
# ================================
# Builds backend and frontend for production deployment

set -euo pipefail

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
BACKEND_DIR="$REPO_DIR/backend"
FRONTEND_DIR="$REPO_DIR/frontend"
BUILD_DIR="$REPO_DIR/build"

echo -e "${BLUE}🏗️  Alça Finanças - Production Build${NC}"
echo ""

# ================================
# Check Production Environment
# ================================
echo -e "${BLUE}==> Checking production environment...${NC}"

if [ ! -f "$REPO_DIR/.env.production" ]; then
    echo -e "${YELLOW}⚠️  .env.production not found${NC}"
    echo -e "${YELLOW}   Using .env (if exists)${NC}"

    if [ ! -f "$REPO_DIR/.env" ]; then
        echo -e "${RED}❌ No environment file found${NC}"
        echo -e "${YELLOW}   Create .env.production with production values${NC}"
        exit 1
    fi
    ENV_FILE="$REPO_DIR/.env"
else
    ENV_FILE="$REPO_DIR/.env.production"
    echo -e "${GREEN}✅ Using .env.production${NC}"
fi

# Load environment
set -a
source "$ENV_FILE"
set +a

# Validate critical variables
REQUIRED_VARS=("SUPABASE_URL" "SUPABASE_SERVICE_ROLE_KEY" "SECRET_KEY")
MISSING_VARS=()

for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var:-}" ]; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -gt 0 ]; then
    echo -e "${RED}❌ Missing required variables:${NC}"
    for var in "${MISSING_VARS[@]}"; do
        echo -e "   - $var"
    done
    exit 1
fi

echo -e "${GREEN}✅ Production environment validated${NC}"
echo ""

# ================================
# Clean Previous Builds
# ================================
echo -e "${BLUE}==> Cleaning previous builds...${NC}"

rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR"

echo -e "${GREEN}✅ Build directory ready${NC}"
echo ""

# ================================
# Build Backend
# ================================
echo -e "${BLUE}==> Building backend...${NC}"

cd "$BACKEND_DIR"

# Create build directory for backend
mkdir -p "$BUILD_DIR/backend"

# Copy backend files (excluding dev files)
echo "  📦 Copying backend files..."
rsync -av \
    --exclude='.venv' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='.pytest_cache' \
    --exclude='tests' \
    --exclude='.coverage' \
    --exclude='htmlcov' \
    --exclude='.env' \
    --exclude='.env.local' \
    ./ "$BUILD_DIR/backend/" > /dev/null

# Copy requirements.txt
cp requirements.txt "$BUILD_DIR/backend/"

echo -e "  ${GREEN}✅ Backend files copied${NC}"

# Create production requirements (no dev dependencies)
echo "  📝 Creating production requirements..."
grep -v "^pytest" requirements.txt | grep -v "^coverage" > "$BUILD_DIR/backend/requirements.prod.txt" || true

echo -e "  ${GREEN}✅ Backend build complete${NC}"
echo ""

# ================================
# Build Frontend
# ================================
echo -e "${BLUE}==> Building frontend...${NC}"

cd "$FRONTEND_DIR"

# Check dependencies
if [ ! -d "node_modules" ]; then
    echo "  📦 Installing frontend dependencies..."
    npm ci --silent
fi

# Set production env for Vite
BACKEND_PORT="${BACKEND_PORT:-8001}"
BACKEND_URL="${VITE_API_URL:-http://localhost:$BACKEND_PORT}"

cat > "$FRONTEND_DIR/.env.production" << EOF
# Auto-generated by scripts/prod/build.sh
VITE_API_URL=$BACKEND_URL
NODE_ENV=production
EOF

echo "  🏗️  Building frontend (this may take a minute)..."
npm run build

# Move build output
echo "  📦 Copying frontend build..."
mkdir -p "$BUILD_DIR/frontend"
cp -r dist/* "$BUILD_DIR/frontend/"

echo -e "  ${GREEN}✅ Frontend build complete${NC}"
echo ""

# ================================
# Generate Build Info
# ================================
echo -e "${BLUE}==> Generating build metadata...${NC}"

GIT_COMMIT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")
BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > "$BUILD_DIR/build-info.json" << EOF
{
  "git_commit": "$GIT_COMMIT",
  "git_branch": "$GIT_BRANCH",
  "build_date": "$BUILD_DATE",
  "node_env": "production",
  "backend_url": "$BACKEND_URL"
}
EOF

echo -e "${GREEN}✅ Build metadata created${NC}"
echo ""

# ================================
# Create Deployment Package
# ================================
echo -e "${BLUE}==> Creating deployment package...${NC}"

cd "$REPO_DIR"

# Create tarball
TARBALL_NAME="alca-financas-$(date +%Y%m%d-%H%M%S).tar.gz"
tar -czf "$TARBALL_NAME" \
    -C "$BUILD_DIR" \
    backend frontend build-info.json

TARBALL_SIZE=$(du -h "$TARBALL_NAME" | cut -f1)

echo -e "${GREEN}✅ Deployment package created${NC}"
echo ""

# ================================
# Summary
# ================================
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Build Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${BLUE}📦 Build Output:${NC}"
echo -e "   Directory:  ${YELLOW}$BUILD_DIR${NC}"
echo -e "   Package:    ${YELLOW}$TARBALL_NAME${NC} ($TARBALL_SIZE)"
echo ""
echo -e "${BLUE}📋 Build Info:${NC}"
echo -e "   Commit:     ${YELLOW}$GIT_COMMIT${NC}"
echo -e "   Branch:     ${YELLOW}$GIT_BRANCH${NC}"
echo -e "   Date:       ${YELLOW}$BUILD_DATE${NC}"
echo ""
echo -e "${BLUE}🚀 Next Steps:${NC}"
echo -e "   1. Test the build locally:"
echo -e "      ${YELLOW}./scripts/prod/run.sh${NC}"
echo -e "   2. Deploy to production:"
echo -e "      ${YELLOW}scp $TARBALL_NAME user@server:/path/${NC}"
echo -e "      ${YELLOW}ssh user@server 'tar -xzf /path/$TARBALL_NAME'${NC}"
echo ""
